site_name: Digital Docs
site_url: https://alphadev14.github.io/digitaldocs/
theme:
  name: material
  logo: assets/logo.png # logo góc trên bên trái
  favicon: assets/logo.png # icon trên tab trình duyệt
nav:
  - Home: index.md
  - Level 1: level1.md
  - Level 2: level2.md
  - Level 3: level3.md
  - Technologies: stack.md
