site_name: P&T | Digital Docs
site_url: https://alphadev14.github.io/digitaldocs/
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
  palette:
    - scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Junior:
      - Backend:
          - ASP.NET Core WebAPI: junior/backend/01-aspnet-core-webapi.md
          - Middleware & Dependency Injection: junior/backend/02-middleware-dependency-injection.md
          - Entity Framework Core: junior/backend/03-entity-framework-core.md
          - LINQ: junior/backend/04-linq.md
          - Authentication (JWT): junior/backend/05-authentication-jwt.md
          - Clean Architecture & SOLID: junior/backend/06-clean-architecture-solid.md
          - Async / Await: junior/backend/07-async-await.md
          - Async / Await 2: junior/backend/08-async-await-2.md
          
      - Frontend:
          - React Basic: junior/frontend/01-react-basic.md
          - React Hooks: junior/frontend/02-react-hooks.md
          - Context API: junior/frontend/03-context-api.md
          - State Management: junior/frontend/04-state-management.md
          - React Router: junior/frontend/05-react-router.md
          - UI (AntD + Tailwind): junior/frontend/06-ui-antd-tailwind.md
          - Responsive & Accessibility: junior/frontend/07-responsive-accessibility.md
          - Testing React: junior/frontend/08-testing-react.md
          - Performance Optimization: junior/frontend/09-performance-optimization.md

      - Database (PostgreSQL):
          - PostgreSQL Basic: junior/database/01-postgresql-basic.md
          - Transactions: junior/database/02-transactions.md
          - Isolation Levels: junior/database/03-isolation-levels.md
          - Index & Partitioning: junior/database/04-index-partitioning.md
          - JSONB in PostgreSQL: junior/database/05-jsonb-postgresql.md
          - Query Optimization: junior/database/06-query-optimization.md
          - PostgreSQL Advanced: junior/database/07-postgresql-advanced.md
      - Testing & Deployment: Testing & Deployment/index.md
      - Project:
          - Todos:
              - Deploy Frontend:
                  - Deploy FE lên Vercel: junior/project/todos/05-deploy-fe.md
              - Deploy Backend:
                  - Deploy BE lên Render: junior/project/todos/06-deploy-be.md
              - Deploy Database:
                  - Deploy Databae lên Render: junior/project/todos/07-deploy-db.md
  - Mid-Level: mid-level/index.md
  - Senior: senior/index.md

plugins: []

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alphadev14
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/your-profile
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@yourchannel
  generator: false

extra_css:
  - extra.css
  - stylesheets/extra.css
